let isLoading = true;
const data = [
  {
    id: 1,
    project: "برمجة ايعازان ال MS-DOS باستخدام لغة CPP",
    supervisor: "م.م. اوغوز محمد حسين",
    year: 2006,
  },
  {
    id: 2,
    project: "image processing using visual basic",
    supervisor: "م.م. اوغوز محمد حسين",
    year: 2006,
  },
  {
    id: 3,
    project: "design simple cpu's",
    supervisor: "م.د. احمد محمد فخرالدين",
    year: 2006,
  },
  {
    id: 4,
    project: "distributed data base for hospital management using sql server",
    supervisor: "م.م. شيماء مصطفى",
    year: 2006,
  },
  {
    id: 5,
    project: "NUMBER THEORY",
    supervisor: "م.هشام اكرام صديق",
    year: 2006,
  },
  {
    id: 6,
    project: "Designing A simple Game Using Visual Basic",
    supervisor: "م.م.اوغوز محمد حسين",
    year: 2006,
  },
  {
    id: 7,
    project: "ضغط البيانات بطريقة هوفمان",
    supervisor: "أ.م.عيسى ابراهيم عيسى الجبوري",
    year: 2006,
  },
  {
    id: 8,
    project: "نظام صرف الرواتب للموظفين عامة حسب النقاط",
    supervisor: "م.م.اوغوز محمد حسين",
    year: 2006,
  },
  {
    id: 9,
    project: "designing and implementation of simple dos shell",
    supervisor: "م.م. اوغوز محمد حسين",
    year: 2007,
  },
  {
    id: 10,
    project: "المجلة العلمية",
    supervisor: "م.م. نهلة جمال حسن",
    year: 2007,
  },
  {
    id: 11,
    project: " معالجة الصور باستخدام قناع (3*3) Image Processing by Using Mask ",
    supervisor: "م.د.احمد محمد فخر الدين ",
    year: 2007,
  },
  {
    id: 12,
    project: "تصميم موقع القاموس ديناميكي باستخدام لغة ASP",
    supervisor: "أ.د. عيسى ابراهيم عيسى",
    year: 2008,
  },
  {
    id: 13,
    project: "design acipher system using RSA method",
    supervisor: "أ.م.د. احمد جالاك شاكر",
    year: 2008,
  },
  {
    id: 14,
    project: "حقيبة تعريفية بنظام التشغيل ( نظام إدارة القرص ) والمكونات المادية للحاسوب",
    supervisor: "أ.د. عيسى ابراهيم عيسى",
    year: 2008,
  },
  {
    id: 15,
    project: "نظام ادارة الأفراد",
    supervisor: "م.د. احمد محمد فخرالدين",
    year: 2008,
  },
  {
    id: 16,
    project: " brightness, saturation and blur",
    supervisor: "أ.م.د. عاصم مجيد مرشد",
    year: 2008,
  },
  {
    id: 17,
    project: "تحليل ملفات الصوت بالامتداد WAV",
    supervisor: "م.م. اوغوز محمد حسين",
    year: 2008,
  },
  {
    id: 18,
    project: "كشف الضوضاء باستخدام بناء خوارزمية الفرق بين صورتين رقميتين",
    supervisor: "د. عبدالله حمود محمد",
    year: 2008,
  },
  {
    id: 19,
    project: "image compression by DCT",
    supervisor: "م.د. شهلة عثمان عمر",
    year: 2008,
  },
  {
    id: 20,
    project: "سجل السيطرة على الموجودات المخزنية الثابتة ",
    supervisor: "أ.د. عيسى ابراهيم عيسى",
    year: 2008,
  },
  {
    id: 21,
    project: "GIF picture analysis",
    supervisor: "م.د. احمد محمد فخرالدين",
    year: 2008,
  },
  {
    id: 22,
    project: "نظام إدارة المكتبة",
    supervisor: "أ.د. برهان فخرالدين جمعة",
    year: 2008,
  },
  {
    id: 23,
    project: "تصميم قاعدة بيانات للطلبة في الكليات والمعاهد",
    supervisor: "أ.د. برهان فخرالدين جمعة",
    year: 2008,
  },
  {
    id: 24,
    project: "package identification how to create active directory server 2003",
    supervisor: "أ.د. عيسى ابراهيم عيسى",
    year: 2008,
  },
  {
    id: 25,
    project: "المحادثة عبر الشبكة ",
    supervisor: "أ.د. عيسى ابراهيم عيسى",
    year: 2008,
  },
  {
    id: 26,
    project: "معالجة الكتب الصادرة والواردة في اي دائرة رسمية",
    supervisor: "م.د. احمد محمد فخرالدين",
    year: 2008,
  },
  {
    id: 27,
    project: "Designing and Implementation of disk maintenance package",
    supervisor: "م.م.اوغوز محمد حسين",
    year: 2008,
  },
  {
    id: 28,
    project: "تصميم قاعدة بيانات لموظفي كلية العلوم بلغة visual fox pro",
    supervisor: "أ.م.عيسى ابراهيم عيسى الجبوري",
    year: 2008,
  },
  {
    id: 29,
    project: "أطلس العراق",
    supervisor: "م.د.احمد محمد فخر الدين ",
    year: 2008,
  },
  {
    id: 30,
    project: "Controlling the Camera Movement",
    supervisor: "أ.د. برهان فخرالدين جمعة",
    year: 2008,
  },
  {
    id: 31,
    project: "حقيبة تعريفية لانشاء دليل نشط لخادم 2003",
    supervisor: "أ.د. عيسى ابراهيم عيسى",
    year: 2008,
  },
  {
    id: 32,
    project: "لتشغيل الملفات الصوتية والفلاشات MAX PLAYER ",
    supervisor: "م.د.احمد محمد فخر الدين ",
    year: 2008,
  },
  {
    id: 33,
    project: "Design aSpecific Web Site Related to the College of Science For E-learning By Using LAN Network",
    supervisor: "أ.م.د. احمد جالاك شاكر",
    year: 2008,
  },
  {
    id: 34,
    project: "تصميم و تمثيل الموجهات في الشبكة المحلية باستخدام لغة فيجوال بيسك ",
    supervisor: "أ.د. عيسى ابراهيم عيسى",
    year: 2008,
  },
  {
    id: 35,
    project: "برنامج السيطرة المخزنية",
    supervisor: "م.د.احمد محمد فخر الدين ",
    year: 2008,
  },
  {
    id: 36,
    project: "Domain Controller for college science based on windows server 2003",
    supervisor: "ضياء الدين صالح",
    year: 2009,
  },
  {
    id: 37,
    project: "tball game by using visual basic",
    supervisor: "م.م. اوغوز محمد حسين",
    year: 2009,
  },
  {
    id: 38,
    project: "graphics using GDI+ and VB.net",
    supervisor: "م.د. احمد محمد فخرالدين",
    year: 2009,
  },
  {
    id: 39,
    project: "design alearning package about the router configuration",
    supervisor: "أ.م.د. احمد جالاك شاكر",
    year: 2009,
  },
  {
    id: 40,
    project: "cipher system method ( encryption and decryption of transmitted text messages )",
    supervisor: "أ.د. برهان فخرالدين جمعة",
    year: 2009,
  },
  {
    id: 41,
    project: "قاموس ذو لغتين عربي-انكليزي\n                  انكليزي-عربي",
    supervisor: "م.د. احمد محمد فخرالدين",
    year: 2009,
  },
  {
    id: 42,
    project: "ASP.NET\ndesigning web site with database by SQL server and ASP.net for imaginary company",
    supervisor: "م.د. احمد محمد فخرالدين",
    year: 2009,
  },
  {
    id: 43,
    project: "design alearning package about the network addressing",
    supervisor: "أ.م.د. احمد جالاك شاكر",
    year: 2009,
  },
  {
    id: 44,
    project: "سيطرة النطاق لكلية العلوم باستخدام نظام ويندوز سيرفر 2003",
    supervisor: "ضياء الدين صالح",
    year: 2009,
  },
  {
    id: 45,
    project: "دراسة Histogram sliding لصور المجهر الرقمية",
    supervisor: "د. عبدالله حمود محمد",
    year: 2009,
  },
  {
    id: 46,
    project: "ادارة مكتب محاماة",
    supervisor: "م.د. احمد محمد فخرالدين",
    year: 2009,
  },
  {
    id: 47,
    project: "تصميم حقيبة تعليمية عن عنونة الشبكات",
    supervisor: "أ.م.د. احمد جالاك شاكر",
    year: 2009,
  },
  {
    id: 48,
    project: "تعلم منطق ال AND للشبكات العصبية باستخدام قانون تعلم ال perceptron",
    supervisor: "م.م. اوغوز محمد حسين",
    year: 2009,
  },
  {
    id: 49,
    project: "تصميم قاعدة بيانات للجنة الامتحانية بنظام اكسس",
    supervisor: "أ.د. برهان فخرالدين جمعة",
    year: 2009,
  },
  {
    id: 50,
    project: "طرح لون من ملفات الصور ذات امتداد JPJ",
    supervisor: "م.م. اوغوز محمد حسين",
    year: 2009,
  },
  {
    id: 51,
    project: "subtracting color from image files JPG format",
    supervisor: "م.م. اوغوز محمد حسين",
    year: 2009,
  },
  {
    id: 52,
    project: "معالجة الضوضاء المصاحبة للصورة الرقمية",
    supervisor: "د. عبدالله حمود محمد",
    year: 2009,
  },
  {
    id: 53,
    project: "develpoing asubnetting software with learning package of IP addressing",
    supervisor: "أ.م.د. احمد جالاك شاكر",
    year: 2009,
  },
  {
    id: 54,
    project: "And rule learning of nns using perceptron learning rule",
    supervisor: "م.م. اوغوز محمد حسين",
    year: 2009,
  },
  {
    id: 55,
    project: "نظام إدارة الإجازات الدورية والزمنية والمرضية",
    supervisor: "م.د. احمد محمد فخرالدين",
    year: 2009,
  },
  {
    id: 56,
    project: "نظام توزيع الطلبة المقبولين على أقسام كلية العلوم",
    supervisor: "م.د. احمد محمد فخرالدين",
    year: 2009,
  },
  {
    id: 57,
    project: "employee's information management system",
    supervisor: "أ.م.د. بابان احمد محمود",
    year: 2010,
  },
  {
    id: 58,
    project: "stego encrypted massage system",
    supervisor: "أ.م.د. احمد جالاك شاكر",
    year: 2010,
  },
  {
    id: 59,
    project: "concluding PUK's for asia cell GSM SIM cards using back propagation learning algorithm",
    supervisor: "م.م. اوغوز محمد حسين",
    year: 2010,
  },
  {
    id: 60,
    project: "design simple game",
    supervisor: "م.د. احمد محمد فخرالدين",
    year: 2010,
  },
  {
    id: 61,
    project: "unicode character recognizer",
    supervisor: "أ.م.د. احمد جالاك شاكر",
    year: 2010,
  },
  {
    id: 62,
    project: "designing anetwork system",
    supervisor: "أ.م.د. بابان احمد محمود",
    year: 2010,
  },
  {
    id: 63,
    project: "enhancement using wavelet transformer",
    supervisor: "م.د. شهلة عثمان عمر",
    year: 2010,
  },
  {
    id: 64,
    project: "designing and implementing asupermarket application system",
    supervisor: "أ.م.د. بابان احمد محمود",
    year: 2010,
  },
  {
    id: 65,
    project: "survey on neural networks and applications",
    supervisor: "م.م. اوغوز محمد حسين",
    year: 2010,
  },
  {
    id: 66,
    project: "تصميم برنامج لحساب الميراث حسب الشريعة الاسلامية",
    supervisor: "م.م. اوغوز محمد حسين",
    year: 2010,
  },
  {
    id: 67,
    project: "image compression using DCT",
    supervisor: "م.د. شهلة عثمان عمر",
    year: 2010,
  },
  {
    id: 68,
    project: "how good are the multi-layer feed-forward neural network",
    supervisor: "م.م. اوغوز محمد حسين",
    year: 2010,
  },
  {
    id: 69,
    project: "designing aweb site database using SQL sever and ASP.net for conference home",
    supervisor: "أ.د. عيسى ابراهيم عيسى",
    year: 2010,
  },
  {
    id: 70,
    project: "image enhacement for improving visibility",
    supervisor: "م.د. ادريس محمد حسين",
    year: 2010,
  },
  {
    id: 71,
    project: "choosing project of student by using database",
    supervisor: "م.د. احمد محمد فخرالدين",
    year: 2010,
  },
  {
    id: 72,
    project: "نظام اللجنة الامتحانية",
    supervisor: "أ.د. عيسى ابراهيم عيسى",
    year: 2010,
  },
  {
    id: 73,
    project: "arabic stego system using diacritics",
    supervisor: "أ.م.د. احمد جالاك شاكر",
    year: 2010,
  },
  {
    id: 74,
    project: "Designing Game",
    supervisor: "د. احمد محمد فخرالدين",
    year: 2010,
  },
  {
    id: 75,
    project: "designing a network system",
    supervisor: "أ.م.د. بابان احمد محمود",
    year: 2010,
  },
  {
    id: 76,
    project: "edge detection by prewitt",
    supervisor: "م.د. شهلة عثمان عمر",
    year: 2010,
  },
  {
    id: 77,
    project: "compressing by huffman and GP-ZIP algorithms",
    supervisor: "أ.د. برهان فخرالدين جمعة",
    year: 2011,
  },
  {
    id: 78,
    project: "uni messenger",
    supervisor: "م.د. عبدالله حمود محمد",
    year: 2011,
  },
  {
    id: 79,
    project: "edge detection by using canny filter",
    supervisor: "م.د. عبدالله حمود محمد",
    year: 2011,
  },
  {
    id: 80,
    project: "Image Enhancement in the Frequency Domain Techniques",
    supervisor: "م.د.عبدالله حمود محمد",
    year: 2011,
  },
  {
    id: 81,
    project: "تحسين الصور بأستخدام Gamma Correction ",
    supervisor: "م.د.عبدالله حمود محمد",
    year: 2011,
  },
  {
    id: 82,
    project: "Tab of the financial system to the presidency of the University of Kirkuk",
    supervisor: "م.د.احمد محمد فخر الدين ",
    year: 2011,
  },
  {
    id: 83,
    project: "Back propagation",
    supervisor: "م.م.اوغوز محمد حسين",
    year: 2011,
  },
  {
    id: 84,
    project: "Design website for Magazine Collage of Science",
    supervisor: "أ.م. ادريس محمد حسين",
    year: 2011,
  },
  {
    id: 85,
    project: "Designing a Web Site Data Base using SQL Server and CSS and ASP.net for Computer World",
    supervisor: "أ.م. ادريس محمد حسين",
    year: 2011,
  },
  {
    id: 86,
    project: "Data Encryption using RSA",
    supervisor: "م.ضمياء عبدالله علوان &م.محمد حميد رشيد",
    year: 2011,
  },
  {
    id: 87,
    project: "Test of most inelegant between two persons",
    supervisor: "م.د. احمد محمد فخرالدين",
    year: 2011,
  },
  {
    id: 88,
    project: "Image Enhancement By Multiple Methods of Contrast",
    supervisor: "م.د.عبدالله حمود محمد",
    year: 2011,
  },
  {
    id: 89,
    project: "Designing Web Page Site with HTML for Collage Science",
    supervisor: "أ.د. عيسى ابراهيم عيسى",
    year: 2011,
  },
  {
    id: 90,
    project: "Distributed Bank Management System",
    supervisor: "م.م.اوغوز محمد حسين",
    year: 2011,
  },
  {
    id: 91,
    project: "Image Techniques Toolkit",
    supervisor: "م.م.اوغوز محمد حسين",
    year: 2011,
  },
  {
    id: 92,
    project: "create student id and management library using barcode",
    supervisor: "م.م. اوغوز محمد حسين",
    year: 2012,
  },
  {
    id: 93,
    project: "استخدام الشبكات العصبية الاصطناعية في تمييز الحروف الانكليزية",
    supervisor: "م.د. ادريس محمد حسين",
    year: 2012,
  },
  {
    id: 94,
    project: "دراسة تأثير الضوضاء على الحافات في الصور التلفزيونية الرقمية وحساب معامل الارتباط",
    supervisor: "م.د. شهلة عثمان عمر",
    year: 2012,
  },
  {
    id: 95,
    project: "نظام حركة المرور ",
    supervisor: "أ.د. برهان فخرالدين جمعة",
    year: 2012,
  },
  {
    id: 96,
    project: "pharmacy project",
    supervisor: "م.د. شهلة عثمان عمر",
    year: 2012,
  },
  {
    id: 97,
    project: "خوارزميات البحث بطريقة Q- LEARNING",
    supervisor: "م. كمال حسن جهاد",
    year: 2012,
  },
  {
    id: 98,
    project: "designing aweb site with HTML & JS & PHP for airline company",
    supervisor: "م.م. محمد حميد رشيد",
    year: 2012,
  },
  {
    id: 99,
    project: "survey wireless networks and its application",
    supervisor: "أ.د. عيسى ابراهيم عيسى",
    year: 2012,
  },
  {
    id: 100,
    project: "Computer science Advertisting system (CSAS)",
    supervisor: "م.محمد حميد رشيد",
    year: 2012,
  },
  {
    id: 101,
    project: "تصميم موقع الكتروني في كلية العلوم قسم الحاسبات",
    supervisor: "م. كمال حسن جهاد",
    year: 2012,
  },
  {
    id: 102,
    project: "wep wireless network hacking",
    supervisor: "م.م. محمد حميد رشيد",
    year: 2012,
  },
  {
    id: 103,
    project: "نظام ادارة الانتخابات آلياً",
    supervisor: "أ.د. عيسى ابراهيم عيسى",
    year: 2012,
  },
  {
    id: 104,
    project: "computer library management system",
    supervisor: "م.د. ادريس محمد حسين",
    year: 2012,
  },
  {
    id: 105,
    project: "نظام شركة الكترونيات",
    supervisor: "م.د. ادريس محمد حسين",
    year: 2012,
  },
  {
    id: 106,
    project: "image enhacement by using linear operator",
    supervisor: "م.د. عبدالله حمود محمد",
    year: 2012,
  },
  {
    id: 107,
    project: "restaurant online reservation website",
    supervisor: "م.م. اوغوز محمد حسين",
    year: 2012,
  },
  {
    id: 108,
    project: "image enhancement in spatial domain using fuzzy technique",
    supervisor: "م.د. عبدالله حمود محمد",
    year: 2012,
  },
  {
    id: 109,
    project: "Cars Agency Management System Using C# Languag ",
    supervisor: "أ.م.عيسى ابراهيم عيسى الجبوري",
    year: 2012,
  },
  {
    id: 110,
    project: "Image Enhancement By using Linear operator",
    supervisor: "م.د. عبدالله حمود محمد",
    year: 2012,
  },
  {
    id: 111,
    project: "برنامج العيادة الذكية",
    supervisor: "م. كمال حسن جهاد",
    year: 2013,
  },
  {
    id: 112,
    project: "networks programming implemention by using c#",
    supervisor: "أ.م.د. محمد حميد رشيد",
    year: 2013,
  },
  {
    id: 113,
    project: "ciphering by using magic squares",
    supervisor: "م.د. شهلة عثمان عمر\nم.م. مجيد حميد الامري",
    year: 2013,
  },
  {
    id: 114,
    project: "pc marketing DBMS using mysq",
    supervisor: "م.د. شهلة عثمان عمر",
    year: 2013,
  },
  {
    id: 115,
    project: "automated blood bank system",
    supervisor: "م. كمال حسن جهاد",
    year: 2013,
  },
  {
    id: 116,
    project: "web page design programming using ASPX.net ( kirkuk hospital as in example )",
    supervisor: "م. سرمد نهاد محمد",
    year: 2013,
  },
  {
    id: 117,
    project: "iq teasting system",
    supervisor: "م.م. اوغوز محمد حسين",
    year: 2013,
  },
  {
    id: 118,
    project: 'face recognition "password"',
    supervisor: "م. كمال حسن جهاد",
    year: 2013,
  },
  {
    id: 119,
    project: "tours and travel call center",
    supervisor: "م.م. زهير نوري محمود",
    year: 2013,
  },
  {
    id: 120,
    project: "تحليل العطاءات المقدم الى شعبة العقود في رئاسة جامعة كركوك",
    supervisor: "م.د. احمد محمد فخرالدين",
    year: 2013,
  },
  {
    id: 121,
    project: "Online Shopping e-Cart",
    supervisor: "م.م. زهير نوري محمود",
    year: 2013,
  },
  {
    id: 122,
    project: "Network Simulation Using OPNET Modular",
    supervisor: "م.م. محمد حميد",
    year: 2013,
  },
  {
    id: 123,
    project: "التحكم بالمروحية عن طريق الحاسوب",
    supervisor: "م. سرمد نهاد محمد",
    year: 2014,
  },
  {
    id: 124,
    project: "نظام ادارة وحدة رياضية",
    supervisor: "أ.م.د. احمد جالاك شاكر",
    year: 2014,
  },
  {
    id: 125,
    project: "التسويق الالكتروني",
    supervisor: "م. عدنان ابراهيم صالح",
    year: 2014,
  },
  {
    id: 126,
    project: "اصدار الوثائق الكترونياً",
    supervisor: "م. عدنان ابراهيم صالح",
    year: 2014,
  },
  {
    id: 127,
    project: "the iris recognition",
    supervisor: "أ.م.د. احمد جالاك شاكر",
    year: 2014,
  },
  {
    id: 128,
    project: "نظام ادارة قوائم اجور الكهرباء",
    supervisor: "م.م. محمد حميد رشيد",
    year: 2014,
  },
  {
    id: 129,
    project: "3d design by visual basic",
    supervisor: "م. كمال حسن جهاد",
    year: 2014,
  },
  {
    id: 130,
    project: "transfere 2D image to 3D map",
    supervisor: "م. كمال حسن جهاد",
    year: 2014,
  },
  {
    id: 131,
    project: "قراءة المتغيرات الفيزيائية برمجياً",
    supervisor: "م. كمال حسن جهاد",
    year: 2014,
  },
  {
    id: 132,
    project: "نظام الحجز الالكتروني المسبق في المستشفيات والعيادات الطبية",
    supervisor: "م. سرمد نهاد محمد",
    year: 2014,
  },
  {
    id: 133,
    project: "نظام التتبع والسيطرة على المركبات",
    supervisor: "م.م. محمد حميد ",
    year: 2014,
  },
  {
    id: 134,
    project: "electricity feeds management system",
    supervisor: "م.م. محمد حميد ",
    year: 2014,
  },
  {
    id: 135,
    project: "نظام الافراد",
    supervisor: "م. عدنان ابراهيم صالح",
    year: 2014,
  },
  {
    id: 136,
    project: "the system of management for students",
    supervisor: "م. عدنان ابراهيم صالح",
    year: 2014,
  },
  {
    id: 137,
    project: "Control Helicopter Via Computer",
    supervisor: "م. سرمد نهاد محمد",
    year: 2014,
  },
  {
    id: 138,
    project: "Intelligent Car Parking System",
    supervisor: "م. كمال حسن جهاد",
    year: 2014,
  },
  {
    id: 139,
    project: "The System of student  Affairs  Management  Electronically",
    supervisor: "م.م.عدنان ابراهيم صالح",
    year: 2014,
  },
  {
    id: 140,
    project: "E-Pre-Booking",
    supervisor: "م. سرمد نهاد محمد",
    year: 2014,
  },
  {
    id: 141,
    project: "System individuals",
    supervisor: "م.م.عدنان ابراهيم صالح",
    year: 2014,
  },
  {
    id: 142,
    project: "نظام ادارة شؤون الطلبة",
    supervisor: "م.م.عدنان ابراهيم صالح",
    year: 2014,
  },
  {
    id: 143,
    project: "Electronic Shopping",
    supervisor: "م.م.عدنان ابراهيم صالح",
    year: 2014,
  },
  {
    id: 144,
    project: "نظام ادارة شؤون الطلبة الكترونيا",
    supervisor: "م.م.عدنان ابراهيم صالح",
    year: 2014,
  },
  {
    id: 145,
    project: "نظام ادارة المكتبة",
    supervisor: "م. كمال حسن جهاد",
    year: 2015,
  },
  {
    id: 146,
    project: "نظام إدارة وارشفة شؤون الموظفين",
    supervisor: "م. عدنان ابراهيم صالح",
    year: 2015,
  },
  {
    id: 147,
    project: "نظام إدارة اللجنة الامتحانية",
    supervisor: "م.م. ديمن يوسف محمود",
    year: 2015,
  },
  {
    id: 148,
    project: "مشروع نظام إدارة قواعد البيانات ( نظام الصيدلية باستخدام mysql ))",
    supervisor: "م.د. شهلة عثمان عمر",
    year: 2015,
  },
  {
    id: 149,
    project: "دليل مدينة كركوك للاجهزة الذكية ( اندرويد )",
    supervisor: "م.م. داليا رعد عباس",
    year: 2015,
  },
  {
    id: 150,
    project: "تحليل وتنفيذ بروتوكول الخادم والعميل",
    supervisor: "م. عدنان ابراهيم صالح",
    year: 2015,
  },
  {
    id: 151,
    project: "الموقع الالكتروني لمذخر الادوية والمستلزمات الطبية",
    supervisor: "م. سرمد نهاد محمد",
    year: 2015,
  },
  {
    id: 152,
    project: "image compression using wavelet transforms",
    supervisor: "م.د. شهلة عثمان عمر",
    year: 2015,
  },
  {
    id: 153,
    project: "guide of the kirkuk city for smart device (android)",
    supervisor: "م.م. داليا رعد عباس",
    year: 2015,
  },
  {
    id: 154,
    project: "تدريب الشبكات العصبية",
    supervisor: "م.د. شهلة عثمان عمر",
    year: 2015,
  },
  {
    id: 155,
    project: "نظام ادارة مذخر ادوية",
    supervisor: "م. سرمد نهاد محمد",
    year: 2015,
  },
  {
    id: 156,
    project: "detection of pencil mark in testing documents",
    supervisor: "د.احمد فريدون فاضل ",
    year: 2015,
  },
  {
    id: 157,
    project: "نظام ادارة مدخر ادوية",
    supervisor: "م.سرمد نهاد محمد",
    year: 2015,
  },
  {
    id: 158,
    project: "electronic hospital",
    supervisor: "م. كمال حسن جهاد",
    year: 2015,
  },
  {
    id: 159,
    project: "online examination system",
    supervisor: "م.م. ديمن يوسف محمود",
    year: 2015,
  },
  {
    id: 160,
    project: "معرض السيارات الكتروني",
    supervisor: "م. سرمد نهاد محمد",
    year: 2015,
  },
  {
    id: 161,
    project: "dss for design lessos schedule",
    supervisor: "أ.م.د. بناز انور قادر",
    year: 2015,
  },
  {
    id: 162,
    project: "training of neural network",
    supervisor: "م.د. شهلة عثمان عمر",
    year: 2015,
  },
  {
    id: 163,
    project: "نظارة ادارة اللجنة الامتحانية ",
    supervisor: "م.م.ايمن يوسف محمود",
    year: 2015,
  },
  {
    id: 164,
    project: "نظام ادارة وارشفة شؤون الموظفين",
    supervisor: "م.م.عدنان ابراهيم صالح",
    year: 2015,
  },
  {
    id: 165,
    project: "نظام دعم القرار لتصميم جدول الدروس ",
    supervisor: "أ.م.د. بناز انور قادر",
    year: 2015,
  },
  {
    id: 166,
    project: " Electronic Hospital",
    supervisor: "أ.م. كمال حسن جهاد",
    year: 2015,
  },
  {
    id: 167,
    project: "CAR SHOPPING ONLINE",
    supervisor: "م.م. سرمد نهاد محمد",
    year: 2015,
  },
  {
    id: 168,
    project: "Library Management System",
    supervisor: "أ.م. كمال حسن جهاد",
    year: 2015,
  },
  {
    id: 169,
    project: "تصميم نظام  دعم القرار الذكي لتشخيص شدة مرض السكري نوع ثاني (Diabetes mellitus)",
    supervisor: "م.م. بناز انور قادر",
    year: 2015,
  },
  {
    id: 170,
    project: "Controlling Electrical Devices Using Mobile phone",
    supervisor: "أ.م. حسين صالح اكبر",
    year: 2015,
  },
  {
    id: 171,
    project: "برنامج لادارة مكتبة لتعليم المجاني لقسم علوم الحاسوب",
    supervisor: "م. سرمد نهاد محمد",
    year: 2016,
  },
  {
    id: 172,
    project: "delegates's system for kirkuk university",
    supervisor: "م. حسين احمد علي",
    year: 2016,
  },
  {
    id: 173,
    project: "university library management system",
    supervisor: "م. كمال حسن جهاد",
    year: 2016,
  },
  {
    id: 174,
    project: "نظام التشفير",
    supervisor: "م. كمال حسن جهاد",
    year: 2016,
  },
  {
    id: 175,
    project: "ادارة سكرتارية القسم الكترونياً",
    supervisor: "م. كمال حسن جهاد",
    year: 2016,
  },
  {
    id: 176,
    project: "elctrical billing system",
    supervisor: "م.م. داليا رعد عباس",
    year: 2016,
  },
  {
    id: 177,
    project: "stores management system for directorate of education",
    supervisor: "م. حسين احمد علي",
    year: 2016,
  },
  {
    id: 178,
    project: "mini facebook site",
    supervisor: "م. بناز انور قادر",
    year: 2016,
  },
  {
    id: 179,
    project: "برنامج قانون الخدمة المدنية نظام علاوات وترفيعات الموظفين",
    supervisor: "م. بناز انور قادر",
    year: 2016,
  },
  {
    id: 180,
    project:
      "the design and implementation process of plane find submitted to the board of the department of computer science",
    supervisor: "م. حسين احمد علي",
    year: 2016,
  },
  {
    id: 181,
    project: "online exam test",
    supervisor: "م. هيام عصام جبرائيل",
    year: 2016,
  },
  {
    id: 182,
    project: "science college's store management system",
    supervisor: "م. بناز انور قادر",
    year: 2016,
  },
  {
    id: 183,
    project: "adaptive the time in the optical signal to reduce traffic congestion",
    supervisor: "م. حسين احمد علي",
    year: 2016,
  },
  {
    id: 184,
    project: "نظام ادارة مكتبات الجامعة",
    supervisor: "م. كمال حسن جهاد",
    year: 2016,
  },
  {
    id: 185,
    project: "برنامج العيادة الالكترونية",
    supervisor: "م. عدنان ابراهيم صالح",
    year: 2016,
  },
  {
    id: 186,
    project: "automatic computer science table",
    supervisor: "م.م. داليا رعد عباس",
    year: 2016,
  },
  {
    id: 187,
    project: "barcode reader using smart phones android",
    supervisor: "م. عدنان ابراهيم صالح",
    year: 2016,
  },
  {
    id: 188,
    project: "electronic management system",
    supervisor: "م. كمال حسن جهاد",
    year: 2016,
  },
  {
    id: 189,
    project: "electronic park management system",
    supervisor: "م. كمال حسن جهاد",
    year: 2016,
  },
  {
    id: 190,
    project: "نظام ادارة مخزن كلية العلوم",
    supervisor: "م. بناز انور قادر",
    year: 2016,
  },
  {
    id: 191,
    project: "حل معادلة فولتيرا الخطية من الدرجة الثانية",
    supervisor: "م.م. مريوان عبدل صالح",
    year: 2016,
  },
  {
    id: 192,
    project: "موقع تواصل الاجتماعي مصغر ",
    supervisor: "م.م. بناز انور قادر",
    year: 2016,
  },
  {
    id: 193,
    project: "تصميم وتنفيد طائرة مسيرة ",
    supervisor: "م.م. حسين احمد علي ",
    year: 2016,
  },
  {
    id: 194,
    project: "نظام الايفادات لجامعة كركوك",
    supervisor: "م.م. حسين احمد علي ",
    year: 2016,
  },
  {
    id: 195,
    project: "image steganography using lsb and edge detection technique",
    supervisor: "م.د. شهلة عثمان عمر",
    year: 2016,
  },
  {
    id: 196,
    project: "نظام إدارة مخازن مديرية التربية",
    supervisor: "م. حسين احمد علي",
    year: 2016,
  },
  {
    id: 197,
    project: "NUMERICAL SOLUTIONS OF LINEAR VOLTERRA INTEGRAL EQUATIONS OF THE SECOND KIND",
    supervisor: "م.م.مريوان عبد الصالح",
    year: 2016,
  },
  {
    id: 198,
    project: "نظام  الادارة الكترونية",
    supervisor: "أ.م. كمال حسن جهاد",
    year: 2016,
  },
  {
    id: 199,
    project: "FINDING SHORTEST PATH BY USING ANT COLONY OPTIMIZATION",
    supervisor: "م.م.عدنان ابراهيم صالح",
    year: 2016,
  },
  {
    id: 200,
    project: "نظام تسجيل البحوث العلمية في جامعة كركوك",
    supervisor: "أ.د. عيسى ابراهيم عيسى",
    year: 2017,
  },
  {
    id: 201,
    project: "detecting of finger print using FFT algorithm",
    supervisor: "م. هيام عصام جبرائيل",
    year: 2017,
  },
  {
    id: 202,
    project: "الكشف عن البصمات باستخدام خوارزمية FFT",
    supervisor: "م. هيام عصام جبرائيل",
    year: 2017,
  },
  {
    id: 203,
    project: "steganography using less significant bit",
    supervisor: "أ.د. عيسى ابراهيم عيسى",
    year: 2017,
  },
  {
    id: 204,
    project: "image forgery detection using SIFT based feartures",
    supervisor: "م.م. نضال محسن هزاع",
    year: 2017,
  },
  {
    id: 205,
    project: "مشروع نظام إدارة قواعد البيانات ( نظام الصيدلية باستخدام mysql ))",
    supervisor: "م. كمال حسن جهاد",
    year: 2017,
  },
  {
    id: 206,
    project: "نظام التحكم في الاجهزة المنزلية عن طريق الرسائل النصية",
    supervisor: " م.م. اوزلام عبدالحكيم محمود",
    year: 2017,
  },
  {
    id: 207,
    project: "محرك بحث مصغر",
    supervisor: "م. بناز انور قادر",
    year: 2017,
  },
  {
    id: 208,
    project: "خوارزميات جدولة وحدة المعالجة المركزية",
    supervisor: "م.م. اوزلام عبدالحكيم محمود",
    year: 2017,
  },
  {
    id: 209,
    project: "CPU scheduling algorithms",
    supervisor: "م.م. اوزلام عبدالحكيم محمود",
    year: 2017,
  },
  {
    id: 210,
    project: "building amulti-clustering map-reduce to analysis data, the type of these data are diverse type",
    supervisor: "م.م. داليا رعد عباس",
    year: 2017,
  },
  {
    id: 211,
    project: "نظام ادارة الحوالات المالية",
    supervisor: "م. حسين احمد علي",
    year: 2017,
  },
  {
    id: 212,
    project: "financial transfer management system",
    supervisor: "م. حسين احمد علي",
    year: 2017,
  },
  {
    id: 213,
    project: "video watermarking using DCT, DWT and FFT algorithms",
    supervisor: "م. هيام عصام جبرائيل",
    year: 2017,
  },
  {
    id: 214,
    project: "design and simulate a lan for college science using packet tracer",
    supervisor: "أ.د. عيسى ابراهيم عيسى",
    year: 2017,
  },
  {
    id: 215,
    project: "نظام تسجيل وتوزيع الطلبة على الاقسام العلمية في كلية العلوم ",
    supervisor: "م.م. كمال حسن جهاد",
    year: 2017,
  },
  {
    id: 216,
    project: "تصميم برنامج لادارة المصروفات الشخصية على نظام الاندرويد",
    supervisor: "م. سرمد نهاد محمد",
    year: 2017,
  },
  {
    id: 217,
    project: "تصميم موقع الكتروني في كلية العلوم لقسم علوم الحاسوب باستخدام لغة php",
    supervisor: "م.م. يلماز نجم الدين طاهر",
    year: 2017,
  },
  {
    id: 218,
    project: "تصميم نظام الكتروني لادارة قسم الثروة الحيوانية في دائرة زراعة كركوك",
    supervisor: "م. حسين احمد علي",
    year: 2017,
  },
  {
    id: 219,
    project: "نظام رواتب الموظفين الذكي",
    supervisor: "م. حسين احمد علي",
    year: 2017,
  },
  {
    id: 220,
    project: "نظام الكتروني لدائرة صحة كركوك",
    supervisor: "م. حسين احمد علي",
    year: 2017,
  },
  {
    id: 221,
    project: "ادارة الالكترونية لشركة انتاج العصائر",
    supervisor: "م. بناز انور قادر",
    year: 2017,
  },
  {
    id: 222,
    project: "تصميم وتنفيذ لوحة المفاتيح باستخدام لغة #C",
    supervisor: "م. سرمد نهاد محمد",
    year: 2017,
  },
  {
    id: 223,
    project: "mini search engine",
    supervisor: "م. بناز انور قادر",
    year: 2017,
  },
  {
    id: 224,
    project: "نظام ادارة المستشفى الكترونياً",
    supervisor: "م. كمال حسن جهاد",
    year: 2017,
  },
  {
    id: 225,
    project: "electronic system of kirkuk health department",
    supervisor: "م. حسين احمد علي",
    year: 2017,
  },
  {
    id: 226,
    project: "Study and Design Restaurant Ordering Management System by using database (MySQL)with C#",
    supervisor: "م.د. شهلة عثمان عمر",
    year: 2017,
  },
  {
    id: 227,
    project: "Electronic Archiving System",
    supervisor: "م.م. داليا رعد عباس",
    year: 2017,
  },
  {
    id: 228,
    project: "Design and Implementation of Web based Library of the college of CSIT",
    supervisor: "أ.م.د. بابان احمد محمود",
    year: 2021,
  },
  {
    id: 229,
    project: "IBDB Internet Books Database",
    supervisor: "م.م. الاء حسن احمد",
    year: 2021,
  },
  {
    id: 230,
    project: "Identity Based Cryptography Using Three Different Key Levels Within Two Phases",
    supervisor: "م.م. كنعان جلال براخاس",
    year: 2021,
  },
  {
    id: 231,
    project: "College Management System",
    supervisor: "م.م. عمار ياسين طعمة",
    year: 2021,
  },
  {
    id: 232,
    project: "Learning Package of Shortest Path Algorithms",
    supervisor: "م.م. الاء حسن احمد",
    year: 2021,
  },
  {
    id: 233,
    project: "The Effects of Camera' s Flash light and Resolution on Image Features",
    supervisor: "م. امين محمد عبد السلام",
    year: 2021,
  },
  {
    id: 234,
    project: "Design and Implementation a Wireless Control System using Android Application",
    supervisor: "أ.م.د. عيسى ابراهيم عيسى",
    year: 2021,
  },
  {
    id: 235,
    project: "Effect of Feature Selection on Deep Learning Model Accuracy",
    supervisor: "م.م.اوغوز محمد حسين",
    year: 2021,
  },
  {
    id: 236,
    project: "Design and Implementing Wireless Transceiver and Network Modeling by using Simulink",
    supervisor: "م.م. اوزلام عبدالحكيم محمود",
    year: 2021,
  },
  {
    id: 237,
    project: "Student Management System",
    supervisor: "م.م. اوزلام عبدالحكيم محمود",
    year: 2021,
  },
  {
    id: 238,
    project: "15 simple projects in arduino with details",
    supervisor: "أ.م.د. احمد حسين تقي",
    year: 2021,
  },
  {
    id: 239,
    project: "Medical Volunteer System",
    supervisor: "م.د. ادريس محمد حسين",
    year: 2021,
  },
  {
    id: 240,
    project: "Smart Shopping System",
    supervisor: "م.د. ادريس محمد حسين",
    year: 2021,
  },
  {
    id: 241,
    project: "Resources and Community for College Students (Web and Mobile app)",
    supervisor: "م. بناز انور قادر",
    year: 2021,
  },
  {
    id: 242,
    project: "Graduation-Project Management System",
    supervisor: "م. بناز انور قادر",
    year: 2021,
  },
  {
    id: 243,
    project: "Chatbot",
    supervisor: "م.م. كامران امين علي",
    year: 2021,
  },
  {
    id: 244,
    project: "SOFTWARE STORE",
    supervisor: "م.م. كامران امين علي",
    year: 2021,
  },
  {
    id: 245,
    project: "The Real estate electronic office application",
    supervisor: "م.م. يلماز نجم الدين طاهر",
    year: 2021,
  },
  {
    id: 246,
    project: "online examination system",
    supervisor: "م.م.محمد فخر الدين عبد القادر",
    year: 2021,
  },
  {
    id: 247,
    project: "PHARMACY STORAGE SYSTEM",
    supervisor: "م.م.محمد فخر الدين عبد القادر",
    year: 2021,
  },
  {
    id: 248,
    project: "Control your home with your smart phone",
    supervisor: "م.م. منى صديق خضر ",
    year: 2021,
  },
  {
    id: 249,
    project: "make adoor lock that works with alaptop using Arduino",
    supervisor: "م.م. منى صديق خضر",
    year: 2021,
  },
  {
    id: 250,
    project: "Bit-level Encryption of Voice by Using Arnold Cat Map and Genetic Algorithm",
    supervisor: "م.م. امجد عجيل هزاع",
    year: 2021,
  },
  {
    id: 251,
    project: "DATA SECURITY USING ENCRYPTION AES",
    supervisor: "م.م.محمد فخر الدين عبد القادر",
    year: 2021,
  },
  {
    id: 252,
    project: "Virtual Rabbit Anatomy Simulator (Windows PC Program)",
    supervisor: "م.م.محمد فخر الدين عبد القادر",
    year: 2021,
  },
  {
    id: 253,
    project: "The Electronic Shop System",
    supervisor: "م.م. يلماز نجم الدين طاهر",
    year: 2021,
  },
  {
    id: 254,
    project: "Smart cooler",
    supervisor: "م.م. منى صديق خضر",
    year: 2021,
  },
  {
    id: 255,
    project: "GPS TRACKING SYSTEM",
    supervisor: "م.م.محمد فخر الدين عبد القادر",
    year: 2021,
  },
  {
    id: 256,
    project:
      "COVID-19 diagnosis using X-ray pictures using convolutional neural networks and machine learning classifiers",
    supervisor: "أ.م.د. احمد حسين تقي",
    year: 2021,
  },
  {
    id: 257,
    project: "(15  simple projects in arduino with details )",
    supervisor: "أ.م.د. احمد حسين تقي",
    year: 2021,
  },
  {
    id: 258,
    project: '"Business Process Optimization - A Call Center Case Study "',
    supervisor: "م.د.شهلة عثمان عمر",
    year: 2022,
  },
  {
    id: 259,
    project: "Advanced Encryption Standard (AES)",
    supervisor: "م.م.ابراهيم محي الدين طه",
    year: 2022,
  },
  {
    id: 260,
    project: "Design and simulate Optical Transmission Medium",
    supervisor: "م.م. اوزلام عبدالحكيم محمود",
    year: 2022,
  },
  {
    id: 261,
    project: " Design Car Speed Detector Using Arduino & IR Sensor ",
    supervisor: "م.م. اوزلام عبدالحكيم محمود",
    year: 2022,
  },
  {
    id: 262,
    project: "Effect of Data Dimensionality  Reduction on Performance of Machine Learning Model ",
    supervisor: "م.م.اوغوز محمد حسين",
    year: 2022,
  },
  {
    id: 263,
    project: "Payroll management system ",
    supervisor: "م.م. الاء حسن احمد",
    year: 2022,
  },
  {
    id: 264,
    project: "Security By Using Steganography Techniques",
    supervisor: "م.م. كنعان جلال براخاس",
    year: 2022,
  },
  {
    id: 265,
    project: "Real Time Face Detection and Recognition Using MATLAB",
    supervisor: "م.م.ابراهيم محي الدين طه",
    year: 2022,
  },
  {
    id: 266,
    project: 'Swarm Intelligence Algorithm for Optimization " Bat Algorithm "',
    supervisor: "م.د.شهلة عثمان عمر",
    year: 2022,
  },
  {
    id: 267,
    project: "Design and Implementation of Security Information System Based on Mobile Communications",
    supervisor: "أ.م.د.عيسى ابراهيم عيسى",
    year: 2022,
  },
  {
    id: 268,
    project: "Mini Amazon",
    supervisor: "م.م. الاء حسن احمد",
    year: 2022,
  },
  {
    id: 269,
    project: "Genetic Algorithm For Optimization",
    supervisor: "م.د.شهلة عثمان عمر",
    year: 2022,
  },
  {
    id: 270,
    project: "Managing and Organizing Information for Graduate Students",
    supervisor: "م.م. الاء حسن احمد",
    year: 2022,
  },
  {
    id: 271,
    project: '" AD - HOC PROTOCOL"',
    supervisor: "أ.م.د.عيسى ابراهيم عيسى",
    year: 2022,
  },
  {
    id: 272,
    project: "Effects of Data Leakage on Machine Learning Algorithm,Classification Case Study .",
    supervisor: "م.م.اوغوز محمد حسين",
    year: 2022,
  },
  {
    id: 273,
    project: "Development History Of Different Mobile Telecommunication System ",
    supervisor: "أ.م.د. عيسى ابراهيم عيسى",
    year: 2022,
  },
  {
    id: 274,
    project: "Copy Move Forgery Image Detection by Using MATLAB",
    supervisor: "م.م.ابراهيم محي الدين طه",
    year: 2022,
  },
  {
    id: 275,
    project: "Student Attendance Management System (SAMS)",
    supervisor: "م.م. كنعان جلال براخاس",
    year: 2022,
  },
  {
    id: 276,
    project: "Development and  evaluation of an improved genetic algorithm",
    supervisor: "م.د.شهلة عثمان عمر",
    year: 2022,
  },
  {
    id: 277,
    project: '"Using Arduino to design Simple Programmable Robotic Arm "',
    supervisor: "م.م. اوزلام عبدالحكيم محمود",
    year: 2022,
  },
  {
    id: 278,
    project: "Bluetooth Localization Network",
    supervisor: "أ.م.د. عيسى ابراهيم عيسى",
    year: 2022,
  },
  {
    id: 279,
    project: "Mall Management System",
    supervisor: "م.م. كامران امين علي",
    year: 2022,
  },
  {
    id: 280,
    project: "Fire Detection System Based on Arduino And GSM Module",
    supervisor: "م.م.محمد فخر الدين عبد القادر",
    year: 2022,
  },
  {
    id: 281,
    project: "Writing and drawing using Arduino",
    supervisor: "م.م. كامران امين علي",
    year: 2022,
  },
  {
    id: 282,
    project: "Smart Home Automation",
    supervisor: "م.م. يلماز نجم الدين طاهر",
    year: 2022,
  },
  {
    id: 283,
    project: "Blood bank mobile application",
    supervisor: "م.م. محمد رشاد",
    year: 2022,
  },
  {
    id: 284,
    project: "SMART PARKING SYSTEM BASED ON ARDUINO",
    supervisor: "م.م. وليد خالد عبد الوهاب",
    year: 2022,
  },
  {
    id: 285,
    project: "RESIDENT CUMP MANAGEMENT",
    supervisor: "م.م.محمد فخر الدين عبد القادر",
    year: 2022,
  },
  {
    id: 286,
    project: "Newborn baby registration website",
    supervisor: "م.م. كامران امين علي",
    year: 2022,
  },
  {
    id: 287,
    project: "Image Segmentation",
    supervisor: "أ.م.د.شهاب احمد ابراهيم",
    year: 2022,
  },
  {
    id: 288,
    project: "Mobile Application Of Enrollment ToEvening Study AT University Of Kirkuk Using Flutter",
    supervisor: "م.م. بناز انور قادر",
    year: 2022,
  },
  {
    id: 289,
    project: "COMPARISON OF ENCRYPTION ALGORITHMS OF TERMS OF SPEED",
    supervisor: "م.م. يوسف محمد وهاب",
    year: 2022,
  },
  {
    id: 290,
    project: "Web Application for Finding Jobs",
    supervisor: "م.م. بناز انور قادر",
    year: 2022,
  },
  {
    id: 291,
    project: "RESTAURANT ORDERING SYSTEM",
    supervisor: "م.م.عدنان يوسف داوود",
    year: 2022,
  },
  {
    id: 292,
    project: "DENOISING IN  IMAGE PROCESSING",
    supervisor: "م.د. شهاب احمد ابراهيم",
    year: 2022,
  },
  {
    id: 293,
    project: "ELECTRONIC MANAGEMENT OF STOCK RECORDS FOR COLLEGE OF COMPUTER SCIENCE",
    supervisor: "د.محمد رشاد بكر",
    year: 2022,
  },
  {
    id: 294,
    project: "Twitter sentiment analysis with topic modeling application",
    supervisor: "د.محمد رشاد بكر",
    year: 2022,
  },
  {
    id: 295,
    project: "ELECTRONIC LIBRARY",
    supervisor: "م.م.عدنان يوسف داوود",
    year: 2022,
  },
  {
    id: 296,
    project: "STUDENT INFORMATION SYSTEM",
    supervisor: "م.م.عدنان يوسف داوود",
    year: 2022,
  },
  {
    id: 297,
    project: "TRACING MOVING GAMERA 360",
    supervisor: "م.م.محمد فخر الدين عبد القادر",
    year: 2022,
  },
  {
    id: 298,
    project: "IMAGE ENCRYPTION USING TRIPLE DES",
    supervisor: "م.د. ادريس محمد حسين",
    year: 2022,
  },
  {
    id: 299,
    project: "ELECTRONIC MEDICAL RECORD",
    supervisor: "م.م.محمد فخر الدين عبد القادر",
    year: 2022,
  },
  {
    id: 300,
    project: "Blood Bank System",
    supervisor: "م.م.محمد فخر الدين عبد القادر",
    year: 2022,
  },
  {
    id: 301,
    project: "Web Application for Airlin Reservations :Kirkuk Airport Case Study ",
    supervisor: "م.م. بناز انور قادر",
    year: 2022,
  },
  {
    id: 302,
    project: "STEGANOGRAPHY OF APPLICATION AND DATA",
    supervisor: "أ.م.د.عيسى ابراهيم عيسى",
    year: 2023,
  },
  {
    id: 303,
    project: "Hiding Information Techniques and its Applications",
    supervisor: "أ.م.د.عيسى ابراهيم عيسى",
    year: 2023,
  },
  {
    id: 304,
    project: "(Total Variation Regulazation in Image Denoising)",
    supervisor: "أ.م.د.شهاب احمد ابراهيم",
    year: 2023,
  },
  {
    id: 305,
    project: "Smart Traffic System",
    supervisor: "م.م. وليد خالد عبد الوهاب",
    year: 2023,
  },
  {
    id: 306,
    project: "Booking Tourism Places By Websites",
    supervisor: "م.م. شالاو فرهاد حسين ",
    year: 2023,
  },
  {
    id: 307,
    project: "Wi-Fi controlled robot ",
    supervisor: "م.م.محمد فخر الدين عبد القادر",
    year: 2023,
  },
  {
    id: 308,
    project: "AI-Powered Web Application for Medical Services",
    supervisor: "م.م. وليد خالد عبد الوهاب",
    year: 2023,
  },
  {
    id: 309,
    project: "LIBRARY MANAGEMENT SYSTEM",
    supervisor: "م.م. وليد خالد عبد الوهاب",
    year: 2023,
  },
  {
    id: 310,
    project: "Student attendance system with NFC",
    supervisor: "م.م. بناز انور قادر",
    year: 2023,
  },
  {
    id: 311,
    project: "PARKING AUTOMATION SYSTEM",
    supervisor: "م.د. اركان خليل شاكر",
    year: 2023,
  },
  {
    id: 312,
    project: "An Application for Student Attendance Using Face Detection Technique",
    supervisor: "م.د.بختيار حسن عبد الرحمن",
    year: 2023,
  },
  {
    id: 313,
    project: "FITNESS CENTER AUTOMATION SYSTEM",
    supervisor: "م.د.بختيار حسن عبد الرحمن",
    year: 2023,
  },
  {
    id: 314,
    project: "An Application for Orders Delivery From Shopping Center In Compounds",
    supervisor: "م.د.بختيار حسن عبد الرحمن",
    year: 2023,
  },
  {
    id: 315,
    project: "Data Protection Using Steganography and Cryptography techniques",
    supervisor: "م.م. كامران امين علي",
    year: 2023,
  },
  {
    id: 316,
    project: "Environmental Monitoring System with LCD Display",
    supervisor: "م.م. منى صديق خضر",
    year: 2023,
  },
  {
    id: 317,
    project: "Image Segmentation by Using Optimization Techniques",
    supervisor: "أ.م.د.شهاب احمد ابراهيم",
    year: 2023,
  },
  {
    id: 318,
    project: "AN ELECTRONIC EDUCATION PLATFORM FOR PROGRAMMING",
    supervisor: "م.م.محمد فخر الدين عبد القادر",
    year: 2023,
  },
  {
    id: 319,
    project: "Electronic Hospital management system",
    supervisor: "م.م.عدنان يوسف داوود",
    year: 2023,
  },
  {
    id: 320,
    project: "Twitter Emotion Recognition System",
    supervisor: "د.محمد رشاد بكر",
    year: 2023,
  },
  {
    id: 321,
    project: "SALES MANAGEMENT SYSTEM",
    supervisor: "م.د.احمد محمد فخر الدين ",
    year: 2023,
  },
  {
    id: 322,
    project: "Segmentation of Images by Otsu Method ",
    supervisor: "أ.م.د.شهاب احمد ابراهيم",
    year: 2023,
  },
  {
    id: 323,
    project: "PC Remote Control",
    supervisor: "م.م.محمد فخر الدين عبد القادر",
    year: 2023,
  },
  {
    id: 324,
    project: 'Design a website for College of Computer Science And Information Technology using html/css"',
    supervisor: "م.م.عدنان يوسف داوود",
    year: 2023,
  },
  {
    id: 325,
    project: "Ball Catching Game",
    supervisor: "م.م. كامران علي امين",
    year: 2023,
  },
  {
    id: 326,
    project: "SAFE HOUSE",
    supervisor: "م.م. اسو احمد مجيد",
    year: 2023,
  },
  {
    id: 327,
    project: "Generate 3D head conductor volume from MRI image using MATLAB ",
    supervisor: "م.م. ابراهيم طه",
    year: 2023,
  },
  {
    id: 328,
    project: "Images and Official Documents Retrieved System from Database Based on Content",
    supervisor: "أ.م.د.أسراء زكي محمد",
    year: 2023,
  },
  {
    id: 329,
    project: "Heart Disease Prediction",
    supervisor: "م.م. اوغوز محمد حسين",
    year: 2023,
  },
  {
    id: 330,
    project: "Database of Cancer Patients And Leukaemia Blood Diseases",
    supervisor: "أ.م.د.أسراء زكي محمد",
    year: 2023,
  },
  {
    id: 331,
    project: "Management Local Networks (Block Some Websites)",
    supervisor: "م.م. مؤمنة صالح ياسين",
    year: 2023,
  },
  {
    id: 332,
    project: "Internet of Things Home Automation Base Cloud Computing",
    supervisor: "أ.م.د. عيسى ابراهيم عيسى",
    year: 2023,
  },
  {
    id: 333,
    project: "Smart Parking System ",
    supervisor: "م.م. اسو احمد مجيد",
    year: 2023,
  },
  {
    id: 334,
    project: "FACE DETECTION IN IMAGES",
    supervisor: "م.م.اوغوز محمد حسين",
    year: 2023,
  },
  {
    id: 335,
    project: "WIRELESS SENSOR NETWORK",
    supervisor: "م.م. أوزلام عبد الحكيم محمود",
    year: 2023,
  },
  {
    id: 336,
    project: "Resturant Management Software",
    supervisor: "م.د.احمد محمد فخر الدين ",
    year: 2023,
  },
  {
    id: 337,
    project: "Design Website for Hospital",
    supervisor: "م.م. مؤمنة صالح ياسين",
    year: 2023,
  },
  {
    id: 338,
    project: "Image Enhancement Using Flutter",
    supervisor: "م.م. مروة نهاد عبدالله ",
    year: 2023,
  },
  {
    id: 339,
    project: "E-voting system using flutter",
    supervisor: "م.م. مروة نهاد عبدالله ",
    year: 2023,
  },
  {
    id: 340,
    project: "Data Encryption (DES) MATLAB Based- 64 Bit Key",
    supervisor: "م.د.شهلة عثمان عمر",
    year: 2023,
  },
  {
    id: 341,
    project: "Patient Booking Management System Using Mobile Application (Lub Dub)",
    supervisor: "أ.م.د. احمد جالاك شاكر",
    year: 2023,
  },
  {
    id: 342,
    project: "Distance Detecting Using Arduino",
    supervisor: "م.م. سعد علي عاصي",
    year: 2024,
  },
  {
    id: 343,
    project: "WATER BILLING MANAGEMENT WEBSITE",
    supervisor: "م.م. يوسف محمد وهاب",
    year: 2024,
  },
  {
    id: 344,
    project: "Electronic Door Lock",
    supervisor: "د.اورهان نور الدين",
    year: 2024,
  },
  {
    id: 345,
    project: "Bluetooth Arduino Car",
    supervisor: "م.د.احمد محمد فخر الدين ",
    year: 2024,
  },
  {
    id: 346,
    project: "CAR STORE WEBSITE",
    supervisor: "م.م. مؤمنة صلاح ياسين",
    year: 2024,
  },
  {
    id: 347,
    project: "Schedule Generator",
    supervisor: "م.م. يوسف محمد وهاب",
    year: 2024,
  },
  {
    id: 348,
    project: "Earthquake detecting using Arduino ",
    supervisor: "م.م. سعد علي عاصي",
    year: 2024,
  },
  {
    id: 349,
    project: "Smart Door Lock System Using Arduino",
    supervisor: "م.د.محمد  رشاد",
    year: 2024,
  },
  {
    id: 350,
    project: "IOT House Management System",
    supervisor: "م.م.علمدار ابراهيم محمد",
    year: 2024,
  },
  {
    id: 351,
    project: "Monitoring the health of patients through Arduino",
    supervisor: "د.احمد مروان العيسى",
    year: 2024,
  },
  {
    id: 352,
    project: "Large Language Model Chatbot with Retrieval Augmented Generation",
    supervisor: "أ.م.د.محمد رشاد",
    year: 2024,
  },
  {
    id: 353,
    project: "Effective Heart Disease Prediction Using Machine Learning Techniques",
    supervisor: "م.م. أرزو محمد مصطفى أمين",
    year: 2024,
  },
  {
    id: 354,
    project: "Design Website For University",
    supervisor: "م.م. مؤمنة صلاح الحديثي",
    year: 2024,
  },
  {
    id: 355,
    project: "A Smart Home Security System Based on Internet of Things",
    supervisor: "د.احمد مروان العيسى",
    year: 2024,
  },
  {
    id: 356,
    project: "Protector Service",
    supervisor: "م.د.شهلة عثمان عمر",
    year: 2024,
  },
  {
    id: 357,
    project: "Pharmacy Management System",
    supervisor: "م.د.احمد محمد فخر الدين ",
    year: 2024,
  },
  {
    id: 358,
    project: "Human Gender Recognition Through Voice Using Machine Learning Algorithms ",
    supervisor: "د.احمد مروان العيسى",
    year: 2024,
  },
  {
    id: 359,
    project: "Beauty Center Management System",
    supervisor: "م.سارا عدنان انور ",
    year: 2024,
  },
  {
    id: 360,
    project: "Student Attendance Management System ",
    supervisor: "م.م. يوسف محمد وهاب",
    year: 2024,
  },
  {
    id: 361,
    project: "Blood Bank Management System",
    supervisor: "م.سارا عدنان انور ",
    year: 2024,
  },
  {
    id: 362,
    project: "Kirkuk Health Care Website",
    supervisor: "م.م. يوسف محمد وهاب",
    year: 2024,
  },
  {
    id: 363,
    project: "Design and Implementation of a Flight Reservation System",
    supervisor: "م.سارا عدنان انور ",
    year: 2024,
  },
  {
    id: 364,
    project: "POLYGRAPH",
    supervisor: "د.اورهان نور الدين",
    year: 2024,
  },
  {
    id: 365,
    project: "SMART HOME BASED ON IOT",
    supervisor: "أ.م.د.عيسى ابراهيم عيسى",
    year: 2024,
  },
  {
    id: 366,
    project: "Mobile Wallet with Merchant Payment Application ",
    supervisor: "د.احسان حسين عبد القادر",
    year: 2024,
  },
  {
    id: 367,
    project: "Employee's Information Management System",
    supervisor: "م.م. وليد خالد عبد الوهاب",
    year: 2024,
  },
  {
    id: 368,
    project: "IMAGE SEGMENTATION USING MATLAB CODING",
    supervisor: "أ.م.د.شهاب احمد ابراهيم",
    year: 2024,
  },
  {
    id: 369,
    project: "Web server based on embedded for controlling home appliances",
    supervisor: "م.د. يوسف أحمد محمد ",
    year: 2024,
  },
  {
    id: 370,
    project: "Academic Advising ",
    supervisor: "م.م.محمد فخر الدين عبد القادر",
    year: 2024,
  },
  {
    id: 371,
    project: "LIBRARY MANAGEMENT SYSTEM",
    supervisor: "م.م. ايفر عبد القادر رشيد",
    year: 2024,
  },
  {
    id: 372,
    project: "DESIGN OF A FIRE PROTECTION USING ARDUINO",
    supervisor: "م.م. منى صديق خضر",
    year: 2024,
  },
  {
    id: 373,
    project: "CAR RENTAL WEBSITE",
    supervisor: "م.م. يلماز نجم الدين طاهر",
    year: 2024,
  },
  {
    id: 374,
    project: "Advantages and Disadvantages of Social Media and the Connection with Education",
    supervisor: "م.م. شالاو فرهاد حسين ",
    year: 2024,
  },
  {
    id: 375,
    project: "Image Denoising by Matlab Coding",
    supervisor: "أ.م.د.شهاب احمد ابراهيم",
    year: 2024,
  },
  {
    id: 376,
    project: "Securing file application",
    supervisor: "م.م. وليد خالد عبد الوهاب",
    year: 2024,
  },
  {
    id: 377,
    project: "Student Information Management System",
    supervisor: "م.م. وليد خالد عبد الوهاب",
    year: 2024,
  },
  {
    id: 378,
    project: "X-Clinic Management System",
    supervisor: "د.احسان حسين عبد القادر",
    year: 2024,
  },
  {
    id: 379,
    project: "PARKING SPACE COUNTER",
    supervisor: "م.د. يوسف أحمد محمد ",
    year: 2024,
  },
  {
    id: 380,
    project: "AUTOMATIC NUMBER PLATE RECOGNITION",
    supervisor: "م.د. يوسف أحمد محمد ",
    year: 2024,
  },
  {
    id: 381,
    project: "GARBAGE MANAGEMENT SYSTEM FOR KIRKUK CITY",
    supervisor: "د.احسان حسين عبد القادر",
    year: 2024,
  },
  {
    id: 382,
    project: "Fake news detection using machine learning",
    supervisor: "م.م. بناز انور قادر",
    year: 2024,
  },
  {
    id: 383,
    project: " Scientific Journal of Computer Science and Information Technology Website of University of Kirkuk",
    supervisor: "م.م. بناز انور قادر",
    year: 2024,
  },
  {
    id: 384,
    project: "DOOR OPENING AND LOCKING CODE USER INTERFACE SCREEN BY ARDUINO AS MICROCONTROLLER",
    supervisor: "م.م. محسن سلمان علي",
    year: 2024,
  },
  {
    id: 385,
    project: "Steganography",
    supervisor: "م.م.محمد فخر الدين عبد القادر",
    year: 2024,
  },
  {
    id: 386,
    project: "Mobile Application  for Pharmacy Database",
    supervisor: "م.م. ايفر عبد القادر رشيد",
    year: 2024,
  },
  {
    id: 387,
    project: "Online store for trading and delivering products",
    supervisor: "م.م. شالاو فرهاد حسين ",
    year: 2024,
  },
  {
    id: 388,
    project: "Design a website to encrypt files using an algorithm",
    supervisor: "م.م. شالاو فرهاد حسين ",
    year: 2024,
  },
  {
    id: 389,
    project: "Calorie System",
    supervisor: "م.م. كامران علي امين",
    year: 2024,
  },
  {
    id: 390,
    project: "Docto،s Electronic Booking Application",
    supervisor: "م.م. يلماز نجم الدين طاهر",
    year: 2024,
  },
  {
    id: 391,
    project: "CHATBOT FOR THE COLLEGE COMPUTER SCINCE & INFORMATION TECHNOLOGY",
    supervisor: " م.م. هوكر خير الله عمر",
    year: 2024,
  },
  {
    id: 392,
    project: "System  of Medical Clinics",
    supervisor: "أ.م.د. بابان احمد محمود",
    year: 2024,
  },
  {
    id: 393,
    project: "Arduino-Based Vehicle Speed Measurement",
    supervisor: "م.م. اوزلام عبدالحكيم محمود",
    year: 2024,
  },
  {
    id: 394,
    project: "Student Record System in PHP",
    supervisor: "م.م. مها محمد عطيه",
    year: 2024,
  },
  {
    id: 395,
    project: "Blood Bank Management System (BBMS)",
    supervisor: "م.م. مها محمد عطيه",
    year: 2024,
  },
  {
    id: 396,
    project: "WEB SCRAPING APPLICATION",
    supervisor: "م.م. مروة نهاد عبدالله",
    year: 2024,
  },
  {
    id: 397,
    project: "Students Data Management Application",
    supervisor: "م.م. عمار ياسين طعمة",
    year: 2024,
  },
  {
    id: 398,
    project: "Human Vein Detection Using Thermal Imaging",
    supervisor: "م.م. ابراهيم محي الدين طه",
    year: 2024,
  },
  {
    id: 399,
    project: "Online Shopping Application",
    supervisor: "م.م. مروة نهاد عبدالله",
    year: 2024,
  },
  {
    id: 400,
    project: "Design and implementatiton of a web application for the Medical Clinic",
    supervisor: "م.م. مرال حسن جمعة",
    year: 2024,
  },
  {
    id: 401,
    project: "Store Management Sale",
    supervisor: "أ.م.د. احمد محمد فخر الدين",
    year: 2024,
  },
  {
    id: 402,
    project: "A Project About Scholarship Management System",
    supervisor: "أ.م.د. بابان احمد محمود",
    year: 2024,
  },
  {
    id: 403,
    project: "Design and Implementation of Web Application for The Graduate Studies Division",
    supervisor: "م.م. مرال حسن جمعة",
    year: 2024,
  },
  {
    id: 404,
    project: "Supervisory control for reconfigurable manufacturing systems: structural change",
    supervisor: "م.د.أنس محمد علي نور الدين",
    year: 2024,
  },
  {
    id: 405,
    project: "IOT:Underground Cable Fault Detector",
    supervisor: "د.أحمد محمود خصر ",
    year: 2024,
  },
  {
    id: 406,
    project: "Pharmacy Management System",
    supervisor: "م.د. احمد محمد فخرالدين",
    year: 2024,
  },
  {
    id: 407,
    project: "Online Doctor Booking Application",
    supervisor: "م.م. سوزان محمد خضير",
    year: 2024,
  },
  {
    id: 408,
    project: "Electronic Birth and Death Management System",
    supervisor: "أ.م.د. اسراء زكي محمد",
    year: 2024,
  },
  {
    id: 409,
    project: "Secondary School Website Database System",
    supervisor: "م.م. مرال حسن جمعة",
    year: 2024,
  },
  {
    id: 410,
    project: "Real -Time Web Search Engine",
    supervisor: "م.م. مروة نهاد عبدالله",
    year: 2024,
  },
  {
    id: 411,
    project: "Computational Neuroscience in Excel using single neuron",
    supervisor: "د.أحمد محمود خضر ",
    year: 2024,
  },
  {
    id: 412,
    project: "Network subnet information",
    supervisor: "ضياء الدين صالح و أ.م.د. عاصم مجيد مرشد",
    year: 2024,
  },
  {
    id: 413,
    project: "تشفير واخفاء النص في الصور",
    supervisor: "م.د.شهلة عثمان عمر",
    year: 2024,
  },
  {
    id: 414,
    project: "IMAGE PROCESSING Image Enhancement by Using Sharpening Spatial Filter",
    supervisor: "م.م.وفاء حازم زكي ",
    year: 2024,
  },
  {
    id: 415,
    project: "Management programme for car reserve material shop",
    supervisor: "م.م. يلماز نجم الدين طاهر",
    year: 2024,
  },
].sort((a, b) => a - b);

function populateYears() {
  const years = [...new Set(data.map((item) => item.year))];
  const yearFilter = document.getElementById("yearFilter");
  years.forEach((year) => {
    const option = document.createElement("option");
    option.value = year;
    option.textContent = year;
    yearFilter.appendChild(option);
  });
}

function filterTable() {
  const selectedYear = document.getElementById("yearFilter").value;
  const tableBody = document.getElementById("tableBody");
  tableBody.innerHTML = "";

  const filteredData = selectedYear === "all" ? data : data.filter((item) => item.year == selectedYear);
  filteredData.forEach((item, index) => {
    const row = `<tr class="border">
            <td class="border p-2 text-center">${index + 1}</td>
            <td class="border p-2 text-center font-bold">${item.project}</td>
            <td class="border p-2 text-center font-bold">${item.supervisor}</td>
            <td class="border p-2 text-center">${item.year}</td>
        </tr>`;
    tableBody.innerHTML += row;
  });
}

const thesis = [
  {
    id: 1,
    name: "احمد رمضان رشيد",
    thesis: "تجزئة الصور الطبية بإستخدام تقنيات الكتلة الهجينه بناء على خوارزميات التعلم",
  },
  {
    id: 2,
    name: "احمد فاضل رشاد",
    thesis: "قياس جودة البرمجيات بإستخدام التعلم الالي بناء على خوارزمية تحسين الخفافيش",
  },
  { id: 3, name: "أزل قصي سعيد", thesis: "استرجاع المعلومات الذكي بالاعتماد على خوارزميات العنقدة" },
  {
    id: 4,
    name: "إسماعيل نامق عثمان",
    thesis: "تحليل المشاعرلخطاب الكراهية على الشبكات الاجتماعية بإستخدام التعلم الالي",
  },
  { id: 5, name: "إنعام عبد الله عبد المجيد", thesis: "نظام كشف الاختراقات بإستخدام خوارزميات التعلم العميق" },
  { id: 6, name: "انمار جميل ناجي", thesis: "تجزئة الصورة بإستخدام دالة متعددة الحدود عالية الترتيب" },
  {
    id: 7,
    name: "بشير مصلح مهدي العبيدي",
    thesis: "منصة مرنة لتقييم نظام هجين من اتصالات الفضاء الحر/والاتصالات اللاسلكية الضوئية",
  },
  {
    id: 8,
    name: "جهاد مجيد نوري",
    thesis: "التعلم العميق القائم على زيادة البيانات للتحقق من التوقيعات المكتوبة بخط اليد دون اتصال بالإنترنيت",
  },
  {
    id: 9,
    name: "جوفين  عثمان نجم",
    thesis: "تحليل أداء نظام كشف التسلل لإنترنيت الأشياء بناء على خوارزمية التعلم الاَلي",
  },
  { id: 10, name: "جيا عمر قادر", thesis: "أكتشاف هجمات حجب الخدمة موزعة باستخدام خوارزميات الذكاء الاصطناعي" },
  {
    id: 11,
    name: "حسين محمد عيسى",
    thesis: "تصنيف الشقوق في صور الكونكريت بإستخدام نماذج الشبكات العصبية الإلتفافية",
  },
  { id: 12, name: "دعاء حيدر مصطفى", thesis: "تعلم الاٌلة غير الموجه لاكتشاف شبكة الروبوتات الخاصه بتدفق البيانات" },
  { id: 13, name: "زمن مولود محمد", thesis: "تصنيف صور خلايا الدم اللوكيميا بإستخدام التعلم الالي" },
  { id: 14, name: "سوزان محمد خضير", thesis: "نموذج أولي آمن لتطبيق ويب للحذف المؤكد في الحوسبة السحابية" },
  { id: 15, name: "شيماء شرف محمد", thesis: "نموذج دعم القرار للتنبؤ بمرض القلب بناءًعلى خوارزميات تعلم الالة" },
  {
    id: 16,
    name: "ضياء حسن خميس",
    thesis: "نظام كشف التطفل على إنترنيت الأشياء في الفضاء الإلكتروني بالاعتماد على تعلم الآلة",
  },
  {
    id: 17,
    name: "عبد الكريم صابر كريم",
    thesis: "عملية التحقق من الشهادة الأكاديمية باستخدام العقد الذكي القائم على تقنية الBlockchain",
  },
  {
    id: 18,
    name: "علي عبد الرحمن صفر",
    thesis: "تمييز الأنماط لمجموعة البيانات الطبية باستخدام الشبكات العصبية متعددة الطبقات",
  },
  {
    id: 19,
    name: "فرح صباح خلف",
    thesis: "تحسين تصنيف بيانات التصوير بالرنين المغناطيسي لسرطان الدماغ باستخدام خوارزميات التعلم الآلي",
  },
  { id: 20, name: "كاوه قمبر عزيز", thesis: "الحذف المؤكد في الحوسبة السحابية" },
  {
    id: 21,
    name: "لؤي مصلح يونس",
    thesis: "تحسين الجيل القادم من الشبكات الضوئية باستخدام التقنيات الهجينة للراديو عبر الألياف",
  },
  { id: 22, name: "محمد احمد محمد", thesis: "التنبؤ بأمراض القلب باستخدام التعلم الجماعي مع تحسين القوة الغاشمة" },
  { id: 23, name: "محمد خلف عبد المجيد", thesis: "أمن الحوسبة السحابية: ترخيص حذف البيانات والمصادقة" },
  {
    id: 24,
    name: "محمد صالح أحمد",
    thesis:
      "تصميم تطبيق تشخيص COVID-19  بإسخدام RESNET50  المستندة الى صور الاشعة السينية للصدر : دراسة حالة مجموعة بيانات كركوك ,العراق",
  },
  { id: 25, name: "محمود معروف احمد", thesis: "توظيف تقنية Blockchain  في نظام إدارة الرواتب في جامعة كركوك" },
  {
    id: 26,
    name: "مرال حسن جمعة",
    thesis: "نظام التصويت الإلكتروني القائم على العقد الذكي باستخدام تقنية الBlockchain",
  },
  { id: 27, name: "مريم احسان رميض عباس", thesis: "طرق هجينة لحل مشاكل تجزئة الصور باستخدام التحسين الشامل" },
  { id: 28, name: "نور اكرم محي الدين", thesis: "أمن الحوسبة السحابية : الحذف المؤكد القائم على السياسة" },
  { id: 29, name: "نور صباح عسكر", thesis: "كشف هجمات التصيد بناء على خوارزمية الغابة العشوائية" },
  { id: 30, name: "هيثم عاصي كريم", thesis: "تحليل تقنيات التنبؤ بأزمة العملة" },
  {
    id: 31,
    name: "ياقوت محسن هزاع",
    thesis: "الشبكة العصبية الالتفافية الفعالة المعتمدة على SMOTE  لكشف التسلل الى الشبكة في البيانات الغير المتوازنة",
  },
  { id: 32, name: "ئالا كودرز رستم", thesis: "طريقة ضغط الصورة أعتماداً على تحليل المويجات الجديدة" },
  { id: 33, name: "سرمد محمود احمد", thesis: "مخطط توزيع المفاتيح لحذف بيانات السحابية بشكل مؤكد" },
  {
    id: 34,
    name: "هيرو عمر احمد",
    thesis: "تحليل المشاعر في الشبكات الاجتماعية غير المتجانسة باستخدام تقنيات التعلم الآلي",
  },
];

function inejectThesis() {
  const thesisTable = document.getElementById("thesisTable");
  thesis.forEach((item, index) => {
    const row = `<tr class="border">
        <td class="border p-2 text-center">${index + 1}</td>
        <td class="border p-2 text-center font-bold">${item.thesis}</td>
        <td class="border p-2 text-center font-bold">${item.name}</td>
    </tr>`;
    thesisTable.innerHTML += row;
  });
}

populateYears();
filterTable();
inejectThesis();

document.addEventListener("DOMContentLoaded", function () {
  document.getElementById("yearFilter").value = "2006";
  filterTable();
});
